# -*- coding: utf-8 -*-
"""NumpyTricks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVeD0z8ZaMr8L5DRSgoJaXsOpAdJw8tE
"""

import numpy as np

#Matriz unidimenssional
mt=np.array([12,34,26,18,10])

print(mt)

print(type(mt))

#Criar uma array com um tipo específico
mtfloat=np.array([1,2,3],dtype=np.float64)

print(mtfloat)

print(type(mtfloat))

#Transformar dados das arrays
mtnew=np.array([1.4,3.6,-5.1,9.42,4.999999])

print(mtnew)

mtnewint=mtnew.astype(np.int32)

print(mtnewint)

#E o inverso
mtmarcha=np.array([1,2,3,4])

print(mtmarcha)

mtnaosei=mtmarcha.astype(np.float64)

print(mtnaosei)

"""# MATRIZ BIDIMENSIONAL"""

#Matriz Bidimensional
mtjoao=np.array([[7,23,2],[12,27,4],[5,34,23]])

print(mtjoao)

#'Empty'
mttha=np.empty([3,2], dtype=int)

print(mttha)

print("--------")

#um
um=np.ones([5,7])

print(um)

#matriz com elementos random
fran=np.random.random((5))

print(fran)

#Outra para números aleatórios
f3s=np.random.default_rng(1)

print(f3s)

f2s=f3s.random(3)

f2s=f3s.random(3)

print(f2s)

#Exemplo para remover repetições
parsafrancis=np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
parsafrancis=np.unique(parsafrancis)

print(parsafrancis)

#Criar raiz quadrada
alexandre=np.array([1,4,9,25,36])

print(np.sqrt(alexandre))

#Exponencial
print(np.exp(alexandre))

#Extração dos Elementos
m=np.array([1,2,3,4,5,6])

#Ele conta 0 1 2 3 4 da esquerda pra direita, Pra saber qual o quarto numero dessa lista
print(m[4])

#Tambem
print(m[-3])

#Extração de Linhas e Colunas, vamos usar a variavel: belo
belo=np.array([[4,5,1],[6,1,7],[7,4,1]])

print(belo)

"""VAMOS EXTRAIR AS LINHAS DE TODAS COLUNAS"""

#primeira linha, todas colunas
belo_linha1=belo[0, -1]

print(belo_linha1)

#Segunda linha todas colunas
belo_linha2=belo[1, :]

print(belo_linha2)

#Terceira linha todas colunas
belo_linha3=belo[2, :]

print(belo_linha3)

"""
VAMOS EXTRAIR AS COLUNAS DE TODAS LINHAS"""

#Primeira Coluna de Todas linhas
belo_coluna1=belo[: ,0]

print(belo_coluna1)